<?php

return [

    'transactions' => [
        'index' => 'Listeleme',
        'create' => 'Ekleme',
        'edit' => 'Düzenleme',
        'destroy' => 'Silme',
        'restored' => 'Geri Alma',
        'forceDeleted' => 'Tamamen Silme',
        'showMenu' => 'Menüde Göster',
        'api' => 'Api İzni',
    ],

    'otherPermissions' => [
        'Logs' => 'Modellere Ait Logları Görebilsin',
        'RemainingBalance' => 'Müşteri Bakiye Yükleme',
        'TicketSale' => 'Bilet Satış Yap',
        'RefundTicket' => 'Bilet İade',
        'TicketReprint' => 'Bileti Tekrar Yazdırma',
        'ShowShift' => 'Vardiya Onaylama',
        'PartnershipBalance' => 'Abonelik Kullanım Hakkı Yükleme',
        'PartnershipMultipleDelete' => 'Toplu Abonelikten Çıkarma',
        'UserImport' => 'Toplu Müşteri Ekleme',
        'PartnershipImport' => 'Toplu Abonelik Tanımlama',
        'PartnershipDelete' => 'Toplu Abonelik Silme',
        'UserStatus' => 'Toplu Müşteri Durum Değiştirme',
        'DashboardGraphics' => 'Dashboard’da Grafikleri Görüntüleme',
        'ShowAllTickets' => 'Tüm Biletleri Görüntüleme',
        'ShowAllUsers' => 'Tüm Müşterileri Görüntüleme',
        'ShowAllRfIdCards' => 'Tüm RFID Kartları Görüntüleme',
        'ShowReportLink' => 'Dashboard Raporlar Bağlantısına Erişebilme',
        'ShowTicketQr' => 'Bilet QR Görüntüleme',
        'LineAnnouncement' => 'Hat Duyurularını Görüntüleme',
    ],

    'reportPermissions' => [
        'DailyTicketReport' => 'Günlük Bilet Satış Raporu',
        'UncheckedTicketReport' => 'Checkin Yapılmamış Biletler',
        'FraudAndUsedTicketReport' => 'Kopya ve Kaçak Bilet Raporu',
        'VehiclePaymentTypeReport' => 'Araç ve Ödeme Tipi Raporu',
        'VehicleLineReport' => 'Araç ve Hat Raporu',
        'VehicleLocationReport' => 'Araç Konumları Raporu',
        'TripPassengerListReport' => 'Sefer Yolcu Listesi',
        'TripStatusListReport' => 'Sefer Durum Listesi',
        'DailyTripDetailReport' => 'Günlük Sefer Detay Raporu',
        'OnTimeDepartureReport' => 'Zamanında Kalkış Raporu',
        'TripUserCountReport' => 'Yolcu Sayısı Raporu',
        'LineEndorsementReport' => 'Hat Ciro Raporu',
        'LinePassingReport' => 'Hat Geçiş Raporu',
        'LineSalesReport' => 'Hat Satış Raporu',
        'LinePaymentTypeReport' => 'Hat ve Ödeme Tipi Raporu',
        'LineUserCountReport' => 'Hat Bazında Yolcu Sayısı',
        'ReceiptSerialReport' => 'Makbuz Seri Raporu',
        'ConsensusReport' => 'Mutabakat Raporu',
        'DailyShiftReport' => 'Günlük Vardiya Raporu',
        'StaffShiftReport' => 'Kullanıcı Vardiya Raporu',
        'UnapprovedShiftReport' => 'Onaylanmamış Vardiya Raporu',
        'PnrReport' => 'PNR Raporu',
        'PartnershipUsageReport' => 'Abonelik Kullanım Raporu',
        'PassingReportMail' => 'Geçiş Raporu Mail',
        'PersonnelWorkingHourReport' => 'Personel Mesai Saatleri Raporu',
        'DailyBalanceReport' => 'Günlük Bakiye Yükleme Raporu',
        'UserBalanceReport' => 'Bakiye Raporu',
        'CampaignUsageReport' => 'Kampanya Kullanım Raporu',
        'RefundReport' => 'İadeler Raporu',
        'OldReports' => 'Eski Raporlar',
    ],

];
